My Portfolio
zakiyousufi/my-Portfolio pull request #4
Opened 2022-05-31 19:11 UTC by zakiyousufi

We created a contact form that
The name field accepts up to 30 chars.
The email field accepts only emails.
The message field accepts up to 500 chars.
All fields have placeholder text.
All fields have the correct type.
A user cannot submit the form if one or more of the fields is empty.

2022-05-31 19:33 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @zakiyousufi,

![AlonzoLeroneThisCloseGIF (2)](https://user-images.githubusercontent.com/50941074/171269977-61042da2-9b2f-488d-8343-bc38baddcb6f.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Correct use of Github workflow
✅ No linter error

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-31 19:33 UTC, AmaduKamara commented on index.html
>          <form class="form">
- [ ] Kindly add the action and method attribute to the form with the action attribute's value having your [Form Spree](https://formspree.io/html/) URL you created on Form Spree and the method is set to POST that allows for posting form data to that Form Spree URL so messages can be sent to your email. Please work on that 👍 
- [ ] Kindly click on the link above, go to the Form Spree website, create your account, then create a form and take the URL of the form created and pass it to your form's action attribute. 👍

2022-05-31 19:33 UTC, AmaduKamara commented on index.html
> +            <textarea class="text-area" placeholder="Enter text here" maxlength="500"></textarea>
- [ ] Kindly add the required attribute to the `textarea` so validation is set on it and users must be able to write you a message before the form can be set.

2022-06-01 11:13 UTC, uwadonat approved these changes
Hi @zakiyousufi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![appr2](https://user-images.githubusercontent.com/65860678/171391577-228095ac-92d3-4533-a247-e9e8b6938d00.gif)

# Status: Approved ✔️✔️✔️

## Optional suggestions
_check inline comments_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-01 11:13 UTC, uwadonat commented on index.html
> +            <textarea class="text-area" placeholder="Enter text here" required></textarea>
- [ ] Use `message` input type on this textarea.

2022-06-01 11:34 UTC, zakiyousufi commented on index.html
> +            <textarea class="text-area" placeholder="Enter text here" required></textarea>
Thank you so mach

2022-06-01 11:43 UTC, merged